import Head from 'next/head'
import Image from 'next/image'
import Section from '../components/Landing'
import About from '../components/About'
import { Inter } from '@next/font/google'
import LandingNavBar from '@/components/LandingNavBar'
import Landing from '../components/Landing'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BoothBuddy 🫶</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingNavBar />
      <Landing/>
      <About></About>
      {/* <Section title="Section 1" description="This is a description" /> */}
      {/* <Section title="Section 1" description="This is a description" /> */}
      
      


      {/* <div className='text-8xl text-blue-300 text-center'>Hello World</div> */}

    </>
  )
}
