import Head from 'next/head'
import Image from 'next/image'
import Section from '../components/Section'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BoothBuddy 🫶</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Section 1" description="This is a description" />
      
      


      {/* <div className='text-8xl text-blue-300 text-center'>Hello World</div> */}

    </>
  )
}
